### ISSUE TITLE
Text wrapping in code examples on site

### ISSUE THREAD

**Issue by andrewesterhuizen** [metalsmith/metalsmith.io#264] opened 2018-01-22 16:29 UTC
The elevator pitch code example and some other examples on the site have their right hand side comments wrapping over to the next line which makes it difficult to read the code. It seems to wrap fine on the smaller breakpoint

Screenshot:
![metalsmith](https://user-images.githubusercontent.com/20419603/35231000-8915782a-ff8f-11e7-9fcf-12f654651d3e.png)

**Comment by Ajedi32** [comment] 2018-01-23 16:52
What browser/OS are you using? It doesn't look that way for me:

![Code with no wrapping](https://user-images.githubusercontent.com/1876931/35288879-8915b5aa-002b-11e8-8d8e-7e053e8dd2f4.png)

**Comment by Ajedi32** [comment] 2018-01-23 16:54
Looks like it might have something to do with the font being used on your PC. Maybe we need to be more specific in the CSS about what font we're using...

**Comment by andrewesterhuizen** [comment] 2018-01-24 09:30
I am on macOS Sierra viewing the site in Chrome but text is wrapping this way in Firefox and Safari too. I tried out some other monospace fonts in the devtools and it is still wrapping. I found that lowering the font size slightly is fixing it so maybe it has something to do with how the font is being rendered on my side

**Comment by axe312ger** [comment] 2018-01-24 09:37
How about a `white-space: no-wrap;` and `overflow: scroll;`?

**Comment by axe312ger** [comment] 2018-01-24 09:37
Fixing it by changing the font size / font family is no real solution. You can't test on all potential devices/browsers

**Comment by Ajedi32** [comment] 2018-01-24 14:54
If we use a specific font loaded via web fonts then all browsers which support web fonts should display the text exactly the same.

`overflow: scroll;` might still be a good idea, just in case, but I'd prefer it if most users don't have to scroll to see all code in that box.

**Comment by axe312ger** [comment] 2018-01-24 15:02
`which support web fonts should display the text exactly the same.`

Nope, sorry, thats wrong. Font rendering differs from OS typ, version, configuration AND zoom level of the user. Even with the exact same font type and size in css.

**Comment by ismay** [comment] 2018-11-02 15:14
@andrewesterhuizen I've tried to reproduce this, but wasn't able to. Are you still encountering this with the current site? We've made some changes, so I'm wondering if that's why I can't reproduce it.

**Comment by andrewesterhuizen** [comment] 2018-11-03 10:09
@ismay Just had a look and it seems to be fixed now

![screenshot 2018-11-03 at 10 04 52](https://user-images.githubusercontent.com/20419603/47950840-469ef380-df50-11e8-9a0d-f7313e4dbdbe.png)

**Comment by ismay** [comment] 2018-11-03 10:13
Nice, thanks for checking. In that case I’ll close it 👍

**Closed by ismay** 2018-11-03 10:13 UTC
Labels: bug
